export const UPDATE_DATA = 'updateData'
export const LOADER = 'loader'
export const SET_FILTER = 'setFilter'
export const OPEN_MODAL = 'openModal'
export const CLOSE_MODAL = 'closeModal'
export const OBSERVER = 'observer'
export const OBSERVER_START = 'observerStart'